/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_exo_analysis_jni_EXOInput */

#ifndef _Included_org_exo_analysis_jni_EXOInput
#define _Included_org_exo_analysis_jni_EXOInput
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_exo_analysis_jni_EXOInput
 * Method:    initialize
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_exo_analysis_jni_EXOInput_initialize
  (JNIEnv *, jobject);

/*
 * Class:     org_exo_analysis_jni_EXOInput
 * Method:    openFile
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_exo_analysis_jni_EXOInput_openFile
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_exo_analysis_jni_EXOInput
 * Method:    search
 * Signature: (JILorg/exo/analysis/jni/JNITPCEvent;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_exo_analysis_jni_EXOInput_search
  (JNIEnv *, jobject, jlong, jint, jobject);

/*
 * Class:     org_exo_analysis_jni_EXOInput
 * Method:    delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_exo_analysis_jni_EXOInput_delete
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
