PKGNAME      = EXOAnalysisJNI
top_builddir ?= ../../..
top_srcdir   = ../../..
DEPENDLIB    = $(if $(findstring no,$(STATIC)),Core) EXOUtilities EXOAnalysisManager dl 

include $(top_builddir)/make/Makefile.inc

